Project/career_roadmap/career_roadmap/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('user.urls')),
    path('', include('tracks.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="user/reset_password/reset_password.html"), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="user/reset_password/reset_password_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="user/reset_password/reset.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="user/reset_password/reset_password_complete.html"), name="password_reset_complete"),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Project/career_roadmap/tracks/urls.py
from django.urls import path
from . import views

urlpatterns = [
 path('',  views.tracks, name='tracks'),
 path('track/<str:pk>/', views.singleTrack, name='single-track'),
 path('add-track/', views.addTrack, name='add-track'),
 path('edit-track/<str:pk>/', views.editTrack, name='edit-track'),
 path('delete-track/<str:pk>/', views.deleteTrack, name='delete-track'),
 path('assign-assessors/<str:pk>/', views.assignAssessors, name='assign-assessors'),
 path('task/<str:pk>/', views.singleTask, name='single-task'),
 path('add-task/<str:pk>/', views.addTask, name='add-task'),
 path('edit-task/<str:pk>/', views.editTask, name='edit-task'),
 path('delete-task/<str:pk>/', views.deleteTask, name='delete-task'),
 path('submit-task/<str:pk>/', views.submitTask, name='submit-task'),
 path('download-file/<str:pk>/', views.downloadFile, name = 'download-file'),
 path('admin-assessor-page/', views.adminAssessorPage, name='admin-assessor-page'),
 path('assessor-page/', views.assessorPage, name='assessor-page'),
 path('assessor-supervise/<str:pk>/', views.assessorSupervise, name='assessor-supervise'),
 path('assess-student-admin/<str:assessor>/<str:pk>/', views.assessStudentAdmin, name='assess-student-admin'),
 path('assess-student/<str:pk>/', views.assessStudent, name='assess-student'),
 path('assess-task-admin/<str:assessor>/<str:pk>/', views.assessTaskAdmin, name='assess-task-admin'),
 path('assess-task/<str:pk>/', views.assessTask, name='assess-task'),
 path('search-page/', views.searchPage, name='search-page'),
 path('add-category/', views.addCategory, name='add-category'),
 path('categories/', views.categories, name='categories'),
 path('edit-category/<str:pk>/', views.editCategory, name='edit-category'),
 path('delete-category/<str:pk>/', views.deleteCategory, name='delete-category'),
 path('download-certificate/<str:pk>/', views.downloadCertificate, name='download-certificate'),
]

Project/career_roadmap/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
 path('', views.loginUser, name='login'),
 path('logout/', views.logoutUser, name='logout'),
 path('register/', views.registerUser, name='register'),
 path('profiles/', views.profiles, name='profiles'),
 path('profile/<str:pk>/', views.profile, name='profile'),
 path('edit-profile/<str:pk>/', views.editProfile, name='edit-profile'),
 path('delete-profile/<str:pk>/', views.deleteProfile, name='delete-profile'),
]

Project/career_roadmap/tracks/models.py
from django.db import models
import uuid
from user.models import Profile, CustomUser

class Category(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.title

class Track(models.Model) :

    id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, primary_key=True)
    created = models.DateTimeField(auto_now_add=True)

    title = models.CharField(max_length=200)
    content = models.TextField(null=True, blank=True)

    students = models.ManyToManyField(Profile, blank=True, related_name='my_tracks')

    author = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    short_intro = models.CharField(max_length=300, null=True)

    category = models.ManyToManyField(Category, related_name='tracks', blank=False)

    def __str__(self) :
        return self.title

class Task(models.Model) :

    id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    track = models.ForeignKey(Track, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=200)
    short_intro = models.CharField(max_length=300)
    content = models.TextField(null=True, blank=True)
    order = models.IntegerField(null=True, blank=True)
    prerequisite = models.ManyToManyField('self', blank=True, symmetrical=False)

    def __str__(self):
        return self.title

class Task_performance(models.Model):
    STATE_CHOICE = (('blocked', 'Not Available'), ('available', 'Available'), ('inProgress', 'In Progress'), ('waiting', 'Waiting'), ('completed','Completed'))
    GRADE_STATE = (('not-graded', 'Not Graded'), ('passed', 'Passed'), ('redo', 'Redo'))
    
    id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, primary_key=True)
    created = models.DateTimeField(auto_now_add=True)

    task = models.ForeignKey(Task, on_delete=models.CASCADE, blank=True, null=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)
    track = models.ForeignKey(Track, on_delete=models.CASCADE, blank=True, null=True)

    status = models.CharField(max_length=20, blank=True, null=True, choices=STATE_CHOICE, default=STATE_CHOICE[0][0])
    grade = models.CharField(max_length=20, blank=True, null=True, choices=GRADE_STATE, default=GRADE_STATE[0][0])

    comment = models.TextField(blank=True, null=True)

    youtube_link = models.CharField(max_length=500, null=True, blank=True)
    github_link = models.CharField(max_length=500, null=True, blank=True)
    submit_file = models.FileField(upload_to='uploads', blank=True, null=True)
    
    def __str__(self):
        return str(self.task.title)
class Certificate(models.Model):
    id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    file = models.FileField(default='certificate_template.jpg', upload_to='uploads/certificates')
    track = models.ForeignKey(Track, on_delete=models.CASCADE)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='my_certificates')

    class Meta:
        ordering = ['-created']
        unique_together = [['owner', 'track']]

    def __str__(self):
        return str(self.track.title)

class Track_assessor(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, primary_key=True)
    created = models.DateTimeField(auto_now_add=True)

    track = models.ForeignKey(Track, on_delete=models.CASCADE, blank=True, null=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return str(self.track)
class Task_assessor(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    track_assessor = models.ForeignKey(Track_assessor, on_delete=models.CASCADE, blank=True, null=True)
    task_performance = models.ForeignKey(Task_performance, on_delete=models.CASCADE, blank=True, null=True)
    def __str__(self):
        return str(self.task_performance)

class MultipleImage(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='markdown_pics', blank=True, null=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, blank=True, null=True)

class Track_review(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    track = models.ForeignKey(Track, on_delete=models.CASCADE)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    rating = models.DecimalField(max_digits=2, decimal_places=1)

    class Meta:
        unique_together = [['owner', 'track']]

Project/career_roadmap/tracks/forms.py
from django import forms
from django.forms import ModelForm
from .models import Track, Task, Task_performance, Category
from user.models import Profile
from django.db.models import Q

class TrackForm(ModelForm):
 class Meta:
  model=Track
  fields=['title', 'short_intro', 'content', 'category']
  widgets={
    'category':forms.CheckboxSelectMultiple(),
  }

class TaskForm(ModelForm):
 class Meta:
  model = Task
  fields = ['title', 'short_intro', 'content', 'prerequisite']
  widgets={
    'prerequisite':forms.CheckboxSelectMultiple(),
  }

 def __init__(self, *args, **kwargs):
    initial = kwargs.get('initial', {})
    super(TaskForm, self).__init__(*args, **kwargs)
    if self.instance.created is None:
      self.fields['prerequisite'].queryset = Task.objects.filter(~Q(id = self.instance.id), track = initial['track'])
    else:
      self.fields['prerequisite'].queryset = Task.objects.filter(~Q(id = self.instance.id), track = self.instance.track)

class TaskSubmitForm(ModelForm):
  class Meta:
    model = Task_performance
    fields = ['github_link', 'youtube_link', 'submit_file']
    labels = {
      'youtube_link':'Youtube link',
      'submit_file':'Your Job',
    }

class TaskAssessForm(ModelForm):
  class Meta:
    model=Task_performance
    fields = ['comment']

class CategoryForm(ModelForm):
  class Meta:
    model=Category
    fields = ['title']

Project/career_roadmap/tracks/templates/tracks/adminAssessorPage.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<p class="page-name">
 <strong>Assessment page</strong>
</p>

<div class="assessor-page">
 {% if results|length > 0 %}
 <div class="students">
  <h2>Assessor{{results|pluralize:"s"}}:</h2>
  {% for result in results %}
  <a href="{% url 'assessor-supervise' result.assessor.id %}" class="student">
   <div class="user-block">
    <div class="user-wrapper">
     <img src="{{result.assessor.profile_image.url}}" alt="avatar">
    </div>
    <div class="full-name">{{result.assessor.first_name}} {{result.assessor.last_name}}</div>

    <div class="stats">
     <div>
      <i class="fa fa-clock-o" aria-hidden="true"></i>
      {{result.waiting}} task{{result.waiting|pluralize:"s"}} not graded
     </div>
     <div class="completed">
      &#10004;
      {{result.completed}} task{{result.completed|pluralize:"s"}} graded
     </div>
    </div>
   </div>
  </a>
  {% endfor %}
  {% include 'pagination.html' with queryset=results page_range=page_range %}
 </div>
 {% else %}
 There is no submissions at the moment
 {% endif %}
</div>

{% endblock %}

Project/career_roadmap/tracks/templates/tracks/assessTask.html
{% extends 'main.html' %}

{% load static %}
{% load track_extra %}
{% load allow_group %}
{% block content %}

<p class="page-name">
 {% if request.user|has_group:"admin" %}
 <a href="{% url 'assess-student-admin' assessor.id profile.id %}">{{profile.first_name}}'s works</a> \
 {% else %}
 <a href="{% url 'assess-student' profile.id %}">{{profile.first_name}}'s works</a> \
 {% endif %}
 <strong>{{task.title}}</strong>
</p>

<div class="single-task assessor">
 <h2>{{task.title}}</h2>

 {% if user_task.status is not None %}
 <div class="status">Status: <span class="{{user_task.status}}">{{user_task.get_status_display}}</span></div>
 {% endif %}

 <p>{{task.short_intro}}</p>

 <div class="content">
  {{task.content|convert_markdown|safe}}
  <hr>
 </div>

 <h3>Assess Student</h3>
 <div class="student_block">
  <a href="{% url 'profile' profile.id %}" class="assessor user-block">
   <div class="user-wrapper">
    <img src="{{profile.profile_image.url}}" alt="">
   </div>
   <div>{{profile.first_name}} {{profile.last_name}}</div>
  </a>
  <div class="submissionLinks waiting">
   {% if user_task.github_link is not None %}
   <div>
    <label>Github link</label>
    {{user_task.github_link}}
   </div>
   {% endif %}

   {% if user_task.youtube_link is not None %}
   <div>
    <label>Youtube link</label>
    <span>{{user_task.youtube_link}}</span>
   </div>
   {% endif %}

   {% if user_task.submit_file != "" %}
   <div>
    <label>Student's work</label>

    <div class="file_block">
     <a class="download-file" href="{% url 'download-file' user_task.id %}">Download</a>
     <div>{{user_task.submit_file}}</div>
    </div>
   </div>
   {% endif %}
  </div>
 </div>

 <form method="POST">
  {% csrf_token %}
  
  <div class="comment_section">
   <div>Add a comment</div>
   {{form.comment}}
  </div>

  <div class="grade_submit">
   <div class="grade_block">
    <label for="id_grade">Grade the work</label>
    <select name="grade" id="id_grade" required>
     <option value="" disabled selected>---------</option>
     <option value="passed">Passed</option>
     <option value="redo">Redo</option>
    </select>
   </div>
   <input type="submit" value="Save" class="submitTask">
  </div>
 </form>

 
</div>
{% endblock %}

Project/career_roadmap/tracks/templates/tracks/assignAssessors.html
{% extends 'main.html' %}
{% block content %}
<div class="assign-users">
<h3>Assign assessors for your track</h3>
<form method="POST">
 {% csrf_token %}
 {% for profile in profiles %}
  <label for="{{profile.id}}" class="user-block">
   <input type="checkbox" name="profile" id="{{profile.id}}" value="{{profile.id}}">
   <div class="container">
    <div class="user-wrapper"><img src="{{profile.profile_image.url}}" alt=""></div>
    {{profile.first_name}} {{profile.last_name}} 
    <div class="profile-email">{{profile.email}}</div>
   </div>
  </label>
  
  
 {% endfor %}

 <br>
 <input type="submit" value="Assign">
</form>
</div>
{% endblock %}

Project/career_roadmap/tracks/templates/tracks/singleTask.html
{% extends 'main.html' %}

{% load static %}
{% load track_extra %}
{% load allow_group %}
{% block content %}


<p class="page-name">
  <a href="{% url 'single-track' task.track.id %}">{{task.track.title}}</a> \
  <strong>{{task.title}}</strong>
</p>

<div class="single-task {{user_task.status}}">
 <div class="first">
  <h2>{{task.title}}
    {% if request.user|has_group:"admin" or request.user|is_author:track.id %}
    <span class="links">
      <a href="{% url 'edit-task' task.id %}">
        <i class="fa fa-pencil" aria-hidden="true"></i>
      </a>
      <a href="#" class="delete">
        <i class="fa fa-trash-o" aria-hidden="true"></i>
      </a>
    </span>
    {% endif %}
  </h2>

  {% if user_task.status is not None %}
  <div class="status">Status: <span class="{{user_task.status}}">{{user_task.get_status_display}}</span></div>
  {% endif %}
</div>
 <div class="stats">
  <div>{{students_num}} students</div>
  <canvas id="canvas" width=400 height=80></canvas>
 </div>
 <p>{{task.short_intro}}</p>

 <!-- if user enrolled into track and not started this task -->
 {% if track in request.user.profile.my_tracks.all %}
  {% if assessors|length == 0 %}
    <div class="color_red">
      Add assessors to the track to start the task
      <a href="{% url 'assign-assessors' track.id %}">here</a>
    </div>
  {% elif user_task.status == 'available'%}
  <form method="POST">
    {% csrf_token %}
    <div class="assessors_block">
      <label for="id_assessors">choose your assessors:</label>
      <select name="assessors" id="id_assessors" required>
        <option value="" disabled selected>Assessors</option>
        {% for assessor in assessors %}
        <option value="{{assessor.id}}">
          {{assessor.profile}}
        </option>
        {% endfor %}
      </select>
    </div>
    <input type="submit" value="Start" class="task-start" name="startTask">
  </form>
  {% endif %}
  {% if user_task.status != 'available' and user_task.status != 'blocked' %}
    <div class="content">
      {{task.content|convert_markdown|safe}}
    </div>
  {% endif %}

  {% if user_task.comment is not None and user_task.comment != "" and user_task.status == 'inProgress' %}
    <div class="feedback-block">
      <div class="flex">
        <h3>Assessors comment</h3>
        <div class="grade">Grade status: <span class="{{user_task.grade}}">{{user_task.get_grade_display}}</span>
        </div>
      </div>
      <div>
        {{user_task.comment}}
      </div>
    </div>
  {% endif %}


  {% if user_task.status == 'inProgress' %}
    <h3>Submission</h3>
    <form method="POST" enctype="multipart/form-data" id="main-form">
      {% csrf_token %}
      <div class="submissionLinks">      
          <div>
            <label for="{{form.github_link.name}}">{{form.github_link.label}}</label>
            {{form.github_link}}
          </div>
          
          <div>
            <label for="{{form.youtube_link.name}}">{{form.youtube_link.label}}</label>
            {{form.youtube_link}}
          </div>

          <div>
            <label for="{{form.submit_file.name}}">{{form.submit_file.label}}</label>
            {{form.submit_file}}
            <div class="file_block">
              <input type="button" value="Browse..." onclick="checkFile()">
              {% if user_task.submit_file == '' %}
                <div id="file-txt">No Files Chosen</div>
              {% else %}
                <div>{{user_task.submit_file}}</div>
              {% endif %}
            </div>
          </div>
      </div>

      {% if user_task.status != 'available' %}
      <div class="assessor user-block">
        <div>Assessor:</div>
        {% for assessor in assigned_assessors %}
        <a href="{% url 'profile' assessor.track_assessor.profile.id %}" class="user-wrapper">
          <img src="{{assessor.track_assessor.profile.profile_image.url}}" alt="">
        </a>
        {% endfor %}
      </div>
      {% endif %}


      <input type="submit" value="Submit" name="submitTask" class="submitTask hidden" id="submitTask">
    </form>
  {% endif %}


  {% if user_task.status == 'waiting' or user_task.status == 'completed' %}
    <h3>Submission</h3>
    <div class="submissionLinks waiting">
      {% if user_task.github_link is not None %}
      <div>
        <label>Github link</label>
        <a href="{{user_task.github_link}}">{{user_task.github_link}}</a>
      </div>
      {% endif %}
    
      {% if user_task.youtube_link is not None %}
      <div>
        <label>Youtube link</label>
        <a href="{{user_task.youtube_link}}">{{user_task.youtube_link}}</a>
      </div>
      {% endif %}
    
      {% if user_task.submit_file != "" %}
      <div>
        <label>Your job</label>
        
        <div class="file_block">
          <a class="download-file" href="{% url 'download-file' user_task.id %}">Download</a>
          <div>{{user_task.submit_file}}</div>
        </div>
      </div>
      {% endif %}
    </div>

    {% if user_task.status != 'available' %}
    <div class="assessor user-block">
      <div>Assessor:</div>
      {% for assessor in assigned_assessors %}
      <a href="{% url 'profile' assessor.track_assessor.profile.id %}" class="user-wrapper">
        <img src="{{assessor.track_assessor.profile.profile_image.url}}" alt="">
      </a>
      {% endfor %}
    </div>
    {% endif %}

    {% if user_task.status == 'waiting' %}
      <div class="waiting end-txt">Wait untill you get your grade...</div>
    {% else %}
      <div class="completed end-txt">Congratulations you have completed this task!!!</div>
    {% endif %}
  {% endif %}
 {% endif %}
 

 {% if prerequisites|length > 0 %}
 <hr>
 <div class="prerequisites">
  <h3>Prerequisites:</h3>
  {% if not track in request.user.profile.my_tracks.all %}
  <p>To get access to this task you have to enroll into {{track.title}} track</p>
  {% elif user_task.status == 'blocked' %}
  <p>To get access to this task you have to complete all prerequisite tasks below</p>
  {% endif %}
   <div class="list">
    {% if track in request.user.profile.my_tracks.all %}
      {% for pr in prerequisites %}
      <a href="{% url 'single-task' pr.task.id %}" class="task-block {{pr.status}}">
        <div class="icon"></div>
        <div class="order">{{pr.task.order}}</div>
        <div class="title">{{pr.task.title}}</div>
      </a>
      {% endfor %}
    {% else %}
      {% for pr in prerequisites %}
      <a href="{% url 'single-task' pr.id %}" class="task-block blocked">
        <div class="icon"></div>
        <div class="order">{{pr.order}}</div>
        <div class="title">{{pr.title}}</div>
      </a>
      {% endfor %}
    {% endif %}
   </div>
 </div>
 {% endif %}
</div>
{% endblock %}

{% block page_scripts %}
<script src="{% static 'js/single_task.js' %}" defer></script>
{{data|json_script:"single-task-passed-data"}}
{% endblock %}

Project/career_roadmap/tracks/templates/tracks/singleTrack.html
{% extends 'main.html' %}

{% load static %}
{% load track_extra %}
{% load allow_group %}
{% block content %}


<p class="page-name">
    <a href="{% url 'tracks'%}">Dashboard</a> \
    <strong>{{track.title}}</strong>
</p>
<div class="single-track">
    <div class="header">
        <h2> {{track.title}}
            {% if request.user|has_group:"admin" or request.user|is_author:track.id %}
                <span class="links">
                    <a href="{% url 'edit-track' track.id %}">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                    </a>
                    <a href="#" class="delete">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </a>
                </span>
            {% endif %}
        </h2>
        {% if track.short_intro is not None %}
            <p>{{track.short_intro}}</p>
        {% endif %}
    
        <div class="track_info">
            <div class="block_1">
                <div class="students_num">{{track.students.all|length}} student{{track.students.all|pluralize:"s"}}</div>
                <div class="track_author">Author: 
                    <a href="{% url 'profile' track.author.id %}">{{track.author.first_name}} {{track.author.last_name}}</a>
                </div>
                {% if rating is not None %}
                    <div class="rating" data-value="{{rating}}">
                        <div class="txt">{{rating}}</div>
                        <div class="rating-display">
                            <i class="star"></i>
                            <i class="star"></i>
                            <i class="star"></i>
                            <i class="star"></i>
                            <i class="star"></i>
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="block_2">
                <div class="stats">100% FREE</div>
                {% if show_certificate %}
                <form method="POST" class="generate">
                    {% csrf_token %}
                    <input type="submit" class="gs-button generate" name="generate" value="Certificate">
                </form>
                
                {% else %}
                <div>Certificate after finishing the track</div>
                {% endif %}
            
                {% if not in_process and request.user.is_authenticated %}
                <form method="POST">
                    {% csrf_token %}
                    <input type="submit" class="gs-button" name="Enroll" value="Enroll">
                </form>
                {% endif %}
            
            </div>
        </div>
    </div>
    <div class="track-content">
        <!-- <h3>Content</h3> -->
        <div>
            {{track.content|convert_markdown|safe}}
        </div>
        
        {% if track in request.user.profile.my_tracks.all %}
        {% if assessors|length == 0 %}
        <div class="color_red">
            Add assessors to the track to start the task
            <a href="{% url 'assign-assessors' track.id %}">here</a>
        </div>
        {% endif %}
        {% if certificate %}
        <div class="download-certificate">
            <img class="certificate" src="{{certificate.file.url}}" alt="">
            <a href="{% url 'download-certificate' certificate.id %}"><span>Download</span></a>
        </div>
        {% endif %}
        {% endif %}
    </div>
    {% if track.task_set.all|length > 0 %}
    <div class="tasks">
        <div class="title_stats">
            <h1>Task{{track.task_set.all|pluralize:"s"}}</h1>

            {% if request.user.is_authenticated %}
            <div class="stats">
                {% if request.user|has_group:"admin" or request.user|is_author:track.id %}
                    <span class="links">
                        <a href="{% url 'add-task' track.id %}">
                            <i class="fa fa-plus" aria-hidden="true"></i>
                            Add task
                        </a>
                    </span>
                {% elif track in request.user.profile.my_tracks.all %}
                    <img src="{% static 'images/icon_correct.png' %}" alt="">
                    <div>14/{{track.task_set.all|length}} tasks done</div>
                {% endif %}
            </div>
            {% endif %}
            </div>
        {% if request.user.is_authenticated and track in request.user.profile.my_tracks.all %}
        <div class="icon_desc">
            <div class="status completed">
                <div class="icon"></div>
                Completed
            </div>
            <div class="status waiting">
                <div class="icon"></div>
                Waiting for grade
            </div>
            <div class="status inProgress">
                <div class="icon"></div>
                In progress
            </div>
            <div class="status available">
                <div class="icon"></div>
                Available
            </div>
            <div class="status blocked">
                <div class="icon"></div>
                Not available
            </div>
        </div>
        <div class="grid">
            {% for user_task in queryset %}
            <a href="{% url 'single-task' user_task.task.id %}" class="task-block {{user_task.status}}">
                <div class="icon"></div>
                <div class="order">{{user_task.task.order}}</div>
                <div class="title">{{user_task.task.title}}</div>
            </a>
            {% endfor %}
        </div>
        {% else %}
            <div class="grid">
                {% for task in queryset %}
                    <a href="{% url 'single-task' task.id %}" class="task-block blocked">
                        <div class="icon"></div>
                        <div class="order">{{task.order}}</div>
                        <div class="title">{{task.title}}</div>
                    </a>
                {% endfor %}
            </div>
        {% endif %}

        {% include 'pagination.html' with queryset=queryset page_range=page_range %}

        

    </div>
    {% elif request.user|has_group:"admin" or request.user|is_author:track.id %}
    <div class="stats">
        <span class="links">
            <a href="{% url 'add-task' track.id %}">
                <i class="fa fa-plus" aria-hidden="true"></i>
                Add task
            </a>
        </span>
    </div>
    {% endif %}

    {% if track.track_review_set.all|length > 0 %}
    <div class="review_block">
        <h1>Review{{ track.track_review_set.all|pluralize:"s" }}</h1>
        <div class="grid {% if track.track_review_set.all|length > 1 %} multiple {% endif %}">
        {% for review in track.track_review_set.all|dictsortreversed:"rating"|slice:":4" %}
            <div class="review">
                <div class="user-block">
                    <div class="user-wrapper">
                        <img src="{{request.user.profile.profile_image.url}}" alt="">
                    </div>
                    <div class="review-owner">
                        <div>{{review.owner.first_name}} {{review.owner.last_name}}</div>

                        <div class="rating" data-value="{{review.rating}}">
                            <div class="rating-display">
                                <i class="star"></i>
                                <i class="star"></i>
                                <i class="star"></i>
                                <i class="star"></i>
                                <i class="star"></i>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="last">
                    {{review.body|slice:"230"}}
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}